version: '3.8'

services:
  audio-transcription-api:
    build: .
    container_name: audio-transcription-api
    ports:
      - "4444:4444"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount a volume for temporary files if needed
      - /tmp/audio-processing:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 