version: '3.8'

services:
  audio-transcription-api:
    build: .
    container_name: audio-transcription-api
    ports:
      - "4443:4443"   # HTTPS only
    environment:
      - PYTHONUNBUFFERED=1
      - SSL_CERT_PATH=/app/certs/fullchain.pem
      - SSL_KEY_PATH=/app/certs/privkey.pem
    volumes:
      # Optional: Mount a volume for temporary files if needed
      - /tmp/audio-processing:/tmp
      # SSL certificates
      - /root/n8n-certs/fullchain.pem:/app/certs/fullchain.pem:ro
      - /root/n8n-certs/privkey.pem:/app/certs/privkey.pem:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:4443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  audio-transcription-frontend:
    build: ./frontend
    container_name: audio-transcription-frontend
    ports:
      - "4446:443"    # HTTPS only
    volumes:
      # SSL certificates
      - /root/n8n-certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /root/n8n-certs/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - audio-transcription-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 